services:
  # Combined Frontend + Backend Service
  - type: web
    name: langbridge-app
    env: node
    buildCommand: cd FRONTEND && npm ci && npm run build && cd ../BACKEND && npm ci --no-optional --legacy-peer-deps
    startCommand: cd BACKEND && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
